# Generated by Django 4.2.2 on 2023-07-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(default='general', max_length=290),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(max_length=100),
        ),
    ]
